Feature/cazb 2867/payment progress screen
InformedSolutions/JAQU-CAZ-Fleets-UI pull request #516
Opened 2020-09-03 07:48 UTC by tkaczu

## Motivation and Context
https://eaflood.atlassian.net/browse/CAZB-2867

## Description
Add payer details to in progress page when somebody from organisation pays for the same CAZ

## How Has This Been Tested?
Manually, proper test cases updated and new added.

## Screenshots (if appropriate):

## Checklist:
- [ ] It contains only changes required by issue (does not contain other PR)
- [ ] Includes link to an issue (if apply)
- [ ] I have added tests to cover my changes.

2020-09-03 08:50 UTC, likeuwill requested changes

2020-09-03 08:50 UTC, likeuwill commented on app/controllers/payments/payments_controller.rb
> +      @user = UsersManagement::User.new(api_response)
we have an email in redis, just fetch it.

2020-09-03 08:50 UTC, likeuwill commented on features/step_definitions/payments_steps.rb
> +end
we already have this method
```
I should be on the Dashboard page
```

2020-09-03 08:50 UTC, likeuwill commented on features/support/mock_users.rb
> +      owner: true,
we dont `owner`, please remove it

2020-09-04 06:40 UTC, likeuwill requested changes

2020-09-04 06:40 UTC, likeuwill commented on app/controllers/payments/payments_controller.rb
> +      # api_response = AccountsApi.user(account_id: caz_lock_account_id, account_user_id: caz_lock_user_id)
no need

2020-09-04 06:40 UTC, likeuwill commented on spec/support/add_to_redis.rb
> +end
this helper will use only one time, please move it to rspec in private section or just in before block

2020-09-04 06:43 UTC, tkaczu commented on spec/support/add_to_redis.rb
> +end
It is used three times in two files - that's why I created this helper, please check:
`spec/requests/payments/payments/in_progress_spec.rb`and `spec/requests/payments/payments/local_authority_spec.rb`

2020-09-04 06:48 UTC, likeuwill approved these changes

2020-09-04 07:00 UTC, merged