[WIP][CAZB-2850] Account Maintenance - Update password page
InformedSolutions/JAQU-CAZ-Fleets-UI pull request #582
Opened 2020-09-24 15:06 UTC by pkalamarski

## Motivation and Context

Parent: https://eaflood.atlassian.net/browse/CAZB-2637
https://eaflood.atlassian.net/browse/CAZB-2850

## Description

## How Has This Been Tested?

## Screenshots (if appropriate):

## Checklist:

- [ ] It contains only changes required by issue (does not contain other PR)
- [ ] Includes link to an issue (if apply)
- [ ] I have added tests to cover my changes.

2020-09-24 16:53 UTC, pkalamarski commented
Implemented in #581

2020-09-28 07:35 UTC, likeuwill requested changes

2020-09-28 07:35 UTC, likeuwill commented on features/account_details/passwords.feature
> +      Then I should be on non primary user account details page
empty line missing

2020-09-28 07:35 UTC, likeuwill commented on app/views/account_details/passwords/edit.html.haml
> +- return_url = current_user.owner ? primary_users_account_details_path : non_primary_users_account_details_path
can u move this logic to `edit` method?

2020-09-28 07:35 UTC, likeuwill commented on app/views/account_details/passwords/edit.html.haml
> +- return_url = current_user.owner ? primary_users_account_details_path : non_primary_users_account_details_path
we need try to escape using such a logic in views when we have space in controllers :)

2020-09-28 07:35 UTC, likeuwill commented on app/controllers/account_details/passwords_controller.rb
> +      url = current_user.owner ? primary_users_account_details_path : non_primary_users_account_details_path
u need this method in two places, so u can add a new method and just use it in `redirect_to url` and in `@back_button_url`

2020-09-28 07:48 UTC, likeuwill approved these changes

2020-09-28 11:14 UTC, merged